<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Mapping.fs" />
		<Compile Include="Database.fs" />
		<Compile Include="Migrations/*.fs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Scaler\Scaler.fsproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper.FSharp" Version="4.9.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="FSharp.Core" Version="9.0.201" />
	</ItemGroup>

</Project>
