// <auto-generated />
namespace Persistence.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Persistence

[<DbContext(typeof<Context.CreatureContext>)>]
[<Migration("20230425145658_CreateTable")>]
type CreateTable() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Creatures"
            ,columns = (fun table -> 
            {|
                name =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                level =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                self =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Creatures", (fun x -> (x.name) :> obj)
                    ) |> ignore
                )
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_Creatures_level"
            ,table = "Creatures"
            ,column = "level"
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Creatures"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "6.0.16") |> ignore

        modelBuilder.Entity("Persistence.Mapping+DatabaseCreature", (fun b ->

            b.Property<string>("name")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.Property<int>("level")
                .IsRequired(true)
                .HasColumnType("INTEGER")
                |> ignore

            b.Property<string>("self")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.HasKey("name")
                |> ignore


            b.HasIndex("level")
                |> ignore

            b.ToTable("Creatures") |> ignore

        )) |> ignore

