// <auto-generated />
namespace Persistence.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Persistence

[<DbContext(typeof<Context.CreatureContext>)>]
type CreatureContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "6.0.16") |> ignore

        modelBuilder.Entity("Persistence.Mapping+DatabaseCreature", (fun b ->

            b.Property<string>("name")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.Property<int>("level")
                .IsRequired(true)
                .HasColumnType("INTEGER")
                |> ignore

            b.Property<string>("self")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.HasKey("name")
                |> ignore


            b.HasIndex("level")
                |> ignore

            b.ToTable("Creatures") |> ignore

        )) |> ignore

